export let recipes = [
  {
    id: 1,
    cuisine: "Indian",
    name: "Paneer Tikka Masala",
    image: "https://res.cloudinary.com/djhnar3ju/image/upload/v1688222043/RecipeGenerator/paneertikkamasala.png",
    ingredients: [
      "250 grams paneer (Indian cottage cheese), cubed",
      "1 cup yogurt",
      "2 tablespoons ginger-garlic paste",
      "1 tablespoon lemon juice",
      "1 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "1 teaspoon ground cumin",
      "1 teaspoon ground coriander",
      "1 cup tomato puree",
      "1 cup heavy cream",
      "2 tablespoons butter",
      "1 tablespoon oil",
      "1 onion, finely chopped",
      "1 green bell pepper, diced",
      "1 red bell pepper, diced",
      "Salt to taste",
      "Fresh coriander leaves for garnishing",
    ],
    instructions: [
      "In a bowl, mix yogurt, ginger-garlic paste, lemon juice, turmeric powder, red chili powder, garam masala, ground cumin, ground coriander, and salt to make a marinade.",
      "Add paneer cubes to the marinade and let it sit for at least 30 minutes.",
      "In a skillet, heat oil and butter over medium heat.",
      "Add chopped onions and sauté until they turn golden brown.",
      "Add the marinated paneer cubes and cook until they become slightly browned.",
      "Add tomato puree and cook for 2-3 minutes.",
      "Add diced bell peppers and cook for another 2-3 minutes until they become tender.",
      "Pour in the heavy cream and simmer for 5-7 minutes.",
      "Adjust salt and spices according to taste.",
      "Garnish with fresh coriander leaves.",
      "Serve hot with naan or rice.",
    ],
  },

  {
    id: 2,
    cuisine: "Indian",

    name: "Vegetable Biryani",
    image: "https://res.cloudinary.com/djhnar3ju/image/upload/v1688222043/RecipeGenerator/vegbiryani.png",
    ingredients: [
      "2 cups basmati rice",
      "1 cup mixed vegetables (carrots, peas, beans, potatoes, etc.), diced",
      "1 onion, thinly sliced",
      "2 tomatoes, chopped",
      "2 tablespoons ghee",
      "2 teaspoons ginger-garlic paste",
      "2 teaspoons biryani masala",
      "1 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "1 cinnamon stick",
      "4 green cardamom pods",
      "4 cloves",
      "10-12 strands of saffron",
      "1/4 cup milk",
      "Salt to taste",
      "Fresh coriander leaves for garnishing",
    ],
    instructions: [
      "Wash the basmati rice and soak it in water for 30 minutes.",
      "Heat ghee in a large pot and add cinnamon stick, cardamom pods, and cloves. Sauté for a minute.",
      "Add sliced onions and sauté until they turn golden brown.",
      "Add ginger-garlic paste and sauté for a minute until the raw smell disappears.",
      "Add chopped tomatoes and cook until they become soft.",
      "Add mixed vegetables, biryani masala, turmeric powder, red chili powder, and garam masala. Mix well.",
      "Drain the soaked rice and add it to the pot. Stir gently to combine the rice with the vegetables and spices.",
      "Add enough water to cook the rice (approximately 3.5 cups). Season with salt.",
      "Cover the pot and cook on low heat until the rice is fully cooked and the flavors are well absorbed.",
      "In a small bowl, mix saffron strands with warm milk and let it sit for a few minutes.",
      "Once the rice is cooked, drizzle the saffron milk over the top. Cover and let it rest for 5 minutes.",
      "Garnish with fresh coriander leaves.",
      "Serve hot with raita or cucumber salad.",
    ],
  },

  {
    id: 3,
    cuisine: "Indian",
    name: "Chana Masala",
    image: "https://res.cloudinary.com/djhnar3ju/image/upload/v1688222043/RecipeGenerator/chanamasala.png",
    ingredients: [
      "2 cups chickpeas (chana), cooked or canned",
      "1 onion, finely chopped",
      "2 tomatoes, pureed",
      "2 teaspoons ginger-garlic paste",
      "2 teaspoons chana masala",
      "1 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon ground cumin",
      "1 teaspoon ground coriander",
      "1 teaspoon garam masala",
      "2 tablespoons oil",
      "1 teaspoon cumin seeds",
      "1 bay leaf",
      "Salt to taste",
      "Fresh coriander leaves for garnishing",
    ],
    instructions: [
      "Heat oil in a pan and add cumin seeds and bay leaf. Sauté until the seeds crackle.",
      "Add chopped onions and sauté until they turn golden brown.",
      "Add ginger-garlic paste and sauté for a minute until the raw smell disappears.",
      "Add tomato puree and cook until the oil separates from the masala.",
      "Add chana masala, turmeric powder, red chili powder, ground cumin, ground coriander, and salt. Mix well.",
      "Add cooked chickpeas and mix them with the masala.",
      "Pour in some water (about 1 cup) and simmer for 10-15 minutes, allowing the flavors to blend.",
      "Sprinkle garam masala and garnish with fresh coriander leaves.",
      "Serve hot with roti or rice.",
    ],
  },

  {
    id: 4,
    cuisine: "Indian",
    name: "Palak Paneer",
    image: "https://res.cloudinary.com/djhnar3ju/image/upload/v1688222043/RecipeGenerator/palakpaneer.png",
    ingredients: [
      "250 grams paneer (Indian cottage cheese), cubed",
      "4 cups spinach leaves",
      "1 onion, finely chopped",
      "2 tomatoes, chopped",
      "2 teaspoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon garam masala",
      "2 tablespoons oil",
      "2 tablespoons butter",
      "Salt to taste",
      "Fresh cream for garnishing",
    ],
    instructions: [
      "Blanch the spinach leaves in boiling water for 2 minutes. Drain and transfer them to a bowl of ice water to retain the color.",
      "Drain the spinach and blend it into a smooth puree.",
      "Heat oil and butter in a pan. Add cumin seeds and sauté until they crackle.",
      "Add chopped onions and sauté until they turn golden brown.",
      "Add ginger-garlic paste and sauté for a minute until the raw smell disappears.",
      "Add chopped tomatoes and cook until they become soft.",
      "Add turmeric powder, red chili powder, and garam masala. Mix well.",
      "Pour in the spinach puree and cook for 5 minutes.",
      "Add paneer cubes and salt. Mix gently, ensuring the paneer is coated with the spinach sauce.",
      "Simmer for another 5 minutes, allowing the flavors to blend.",
      "Garnish with a swirl of fresh cream.",
      "Serve hot with naan or rice.",
    ],
  },

  {
    id: 5,
    cuisine: "Indian",

    name: "Aloo Gobi",
    image: "https://res.cloudinary.com/djhnar3ju/image/upload/v1688222043/RecipeGenerator/aloogobi.png",
    ingredients: [
      "2 cups cauliflower florets",
      "2 medium-sized potatoes, peeled and cubed",
      "1 onion, finely chopped",
      "2 tomatoes, chopped",
      "2 teaspoons ginger-garlic paste",
      "1 teaspoon cumin seeds",
      "1 teaspoon turmeric powder",
      "1 teaspoon red chili powder",
      "1 teaspoon ground cumin",
      "1 teaspoon ground coriander",
      "1/2 teaspoon garam masala",
      "2 tablespoons oil",
      "Salt to taste",
      "Fresh coriander leaves for garnishing",
    ],
    instructions: [
      "Heat oil in a pan and add cumin seeds. Sauté until they crackle.",
      "Add chopped onions and sauté until they turn golden brown.",
      "Add ginger-garlic paste and sauté for a minute until the raw smell disappears.",
      "Add chopped tomatoes and cook until they become soft.",
      "Add turmeric powder, red chili powder, ground cumin, ground coriander, and salt. Mix well.",
      "Add cauliflower florets and cubed potatoes. Mix gently to coat them with the masala.",
      "Cover the pan and cook on low heat for about 20-25 minutes or until the vegetables are tender, stirring occasionally.",
      "Sprinkle garam masala and mix well.",
      "Garnish with fresh coriander leaves.",
      "Serve hot with roti or rice.",
    ],
  },
];
